"""
Build script for BEAM.
Usage:
    uv run python build.py          # build beamtel + package mod
    uv run python build.py --mod    # package mod only (skip nuitka)
    uv run python build.py --exe    # build beamtel only (skip mod)

Portability notes:
  * Output goes to ``build/`` inside the project (created if missing) — there is
    no dependency on any machine-specific folder.
  * ``bng_mod`` is expected to be a directory junction pointing at BeamNG's
    standard unpacked-mods location. If it is missing the script creates the
    junction automatically (see ``ensure_mod_junction``).
"""

import argparse
import datetime
import json
import os
import re
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

PROJECT_DIR = Path(__file__).parent.resolve()
# Nuitka writes beamtel.exe here (see --output-dir in beamtel.py's pragmas), and
# this is also where we stage everything that gets bundled into the release zip.
BUILD_DIR = PROJECT_DIR / "build"
OUTPUT_DIR = BUILD_DIR
MOD_JUNCTION = PROJECT_DIR / "bng_mod"

# The folder name BeamNG expects once the mod zip is unpacked. Deliberately a
# constant rather than the resolved directory's name: locally ``bng_mod`` is a
# junction into .../unpacked/bng_screenreader_mod and the two agree, but on a CI
# checkout the tracked ``bng_mod/`` directory is the real thing and the derived
# name would silently become "bng_mod".
MOD_ZIP_NAME = "bng_screenreader_mod.zip"

# Stamped into the mod zip by package_mod() and read back by
# config_ui.install_mod_interactive(). Without it the only thing distinguishing
# two mod zips is their FILE MTIME, which is not a version: shutil.copy2 (the
# installer) preserves it verbatim, so it travels between machines and means
# whatever some other computer's clock said; zipfile.extractall (the updater's
# stage step) does not restore it at all and invents "now"; and robocopy carries
# whatever it is handed. Comparing those decides which build is newer by
# comparing clocks, which is how a freshly downloaded release came to be
# reported as older than the copy it was replacing.
MOD_VERSION_MEMBER = "bnvda_mod_version.json"

# Release bundle name. Fixed, with no date in it, so that
# <repo>/releases/latest/download/BeamNG_accessibility_mod.zip is a permanent
# link to the newest tagged build.
BUNDLE_NAME = "BeamNG_accessibility_mod.zip"

# Data files Nuitka pulls in via --include-data-file (paths are relative to the
# project dir at build time). The .npz is generated by bake_hrtf.py from the
# .sofa file, but unlike the .sofa it is committed — which is what lets a bare
# checkout (CI included) build with no h5py. Checked anyway, so a build missing
# it fails here with a clear message rather than deep inside Nuitka. The speech
# library is no longer in this list: Prism ships inside the prismatoid wheel, so
# `uv sync` provides it.
REQUIRED_BUILD_INPUTS = ("hrtf_kemar_horizontal.npz",)

# Nuitka scratch directories that may appear in BUILD_DIR; never bundle these, and
# never let them leak into the release zip. ".appdata" is the onefile runtime
# unpack folder created when the exe is *run* from BUILD_DIR.
SCRATCH_SUFFIXES = (".dist", ".build", ".onefile-build")
SCRATCH_NAMES = {".appdata", "__pycache__"}

# --- Machine-specific build tuning (edit per machine) ---
# These used to live as "# nuitka-project:" pragmas at the top of beamtel.py, but the
# ones below differ between machines, so they are surfaced here instead.
#
# Each of these can be overridden from the environment, so a machine that is not
# this one -- CI, most obviously -- configures the build without editing the
# tracked defaults.
#
# Compiler backend: "clang" -> pass --clang; "msvc" -> Nuitka's default MSVC (no flag).
COMPILER = os.environ.get("BEAM_COMPILER", "clang")

# UPX executable compression. If USE_UPX is True but UPX_BINARY does not exist,
# UPX is skipped with a warning instead of failing the build.
USE_UPX = os.environ.get("BEAM_UPX", "1") != "0"
UPX_BINARY = os.environ.get("BEAM_UPX_BINARY", r"C:\upx-5.2.0-win64\upx.exe")

# Parallel Nuitka jobs.
NUITKA_JOBS = int(os.environ.get("BEAM_NUITKA_JOBS", "12"))


def beamng_mod_target() -> Path:
    """Standard per-user location of the unpacked screen-reader mod.

    %LOCALAPPDATA%\\BeamNG\\BeamNG.drive\\current\\mods\\unpacked\\bng_screenreader_mod
    'current' is a stable junction BeamNG maintains pointing at the active version,
    so this path is the same on every machine.
    """
    local = os.environ.get("LOCALAPPDATA") or os.path.join(
        os.path.expanduser("~"), "AppData", "Local"
    )
    return (
        Path(local)
        / "BeamNG"
        / "BeamNG.drive"
        / "current"
        / "mods"
        / "unpacked"
        / "bng_screenreader_mod"
    )


def ensure_mod_junction() -> bool:
    """Make sure ``bng_mod`` resolves to BeamNG's mods folder.

    - If it already exists (a junction, or a real folder materialized by git),
      leave it alone and just report where it points.
    - If a broken junction is present, remove it and recreate.
    - If it is missing entirely, create a junction to the standard location
      (provided that location exists).
    """
    target = beamng_mod_target()

    if os.path.exists(MOD_JUNCTION):
        resolved = Path(os.path.realpath(MOD_JUNCTION))
        print(f"Mod junction OK: {MOD_JUNCTION.name} -> {resolved}")
        if resolved != target and resolved != target.resolve():
            print(
                "  NOTE: it does not point at the standard BeamNG location\n"
                f"        ({target}). Leaving it as-is."
            )
        return True

    # Path may be a dangling junction (link present, target gone): exists() is
    # False but lexists() is True. Clear it so mklink can recreate it.
    if os.path.lexists(MOD_JUNCTION):
        print(f"Removing dangling junction at {MOD_JUNCTION}")
        try:
            os.rmdir(MOD_JUNCTION)
        except OSError:
            try:
                os.remove(MOD_JUNCTION)
            except OSError as e:
                print(f"ERROR: could not remove existing {MOD_JUNCTION}: {e}")
                return False

    if not target.exists():
        print(
            "ERROR: cannot create the mod junction because BeamNG's mod folder\n"
            f"       was not found at:\n         {target}\n"
            "       Install/spawn the mod in BeamNG once (so the folder exists),\n"
            "       or create the 'bng_mod' junction manually, then re-run."
        )
        return False

    print(f"Creating junction: {MOD_JUNCTION} -> {target}")
    result = subprocess.run(
        ["cmd", "/c", "mklink", "/J", str(MOD_JUNCTION), str(target)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"ERROR: mklink failed: {result.stdout.strip()} {result.stderr.strip()}")
        return False
    return True


def prism_native_dir() -> Path | None:
    """Locate the installed prismatoid package's native payload directory."""
    candidate = PROJECT_DIR / ".venv" / "Lib" / "site-packages" / "prism" / "_native"
    if candidate.is_dir():
        return candidate
    try:
        import prism

        fallback = Path(prism.__file__).parent / "_native"
        if fallback.is_dir():
            return fallback
    except Exception:
        pass
    return None


def python3_dll() -> Path | None:
    """Locate python3.dll, the stable-ABI forwarder.

    prismatoid ships an abi3 wheel, so _prism_cffi.pyd imports python3.dll
    rather than python313.dll. Nuitka bundles only the version-specific
    python313.dll, and without the forwarder the extension fails to load with
    a bare "DLL load failed while importing _prism_cffi".
    """
    result = subprocess.run(
        ["uv", "run", "python", "-c", "import sys; print(sys.base_prefix)"],
        cwd=PROJECT_DIR,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return None
    candidate = Path(result.stdout.strip()) / "python3.dll"
    return candidate if candidate.is_file() else None


def prism_nuitka_args() -> list[str] | None:
    """Nuitka flags that get Prism's native payload into the distribution.

    Prism keeps prism.dll and its CFFI extension in a `_native` subdirectory
    that prism/_native.py splices onto the package __path__ at import time.
    Nuitka's static import resolution cannot follow that, and --include-data-dir
    silently drops binaries (it copies only the link-time prism.lib), so both
    files are named explicitly as data files at the paths Prism expects.
    """
    native = prism_native_dir()
    if native is None:
        print(
            "ERROR: could not locate prism/_native. Run 'uv sync' so the\n"
            "       prismatoid wheel is installed before building."
        )
        return None
    forwarder = python3_dll()
    if forwarder is None:
        print("ERROR: could not locate python3.dll next to the interpreter.")
        return None
    return [
        "--include-package=prism",
        "--include-package=cffi",
        f"--include-data-files={native / 'prism.dll'}=prism/_native/prism.dll",
        f"--include-data-files={native / '_prism_cffi.pyd'}"
        "=prism/_native/_prism_cffi.pyd",
        f"--include-data-files={forwarder}=python3.dll",
    ]


def check_build_inputs() -> bool:
    """Verify the data files Nuitka needs are present before kicking off a build."""
    missing = [name for name in REQUIRED_BUILD_INPUTS if not (PROJECT_DIR / name).exists()]
    if missing:
        print("ERROR: required build input(s) missing from the project directory:")
        for name in missing:
            print(f"  - {name}")
        print(
            "\nNote: hrtf_kemar_horizontal.npz is committed to the repo; if it is\n"
            "missing, regenerate it from the .sofa file with bake_hrtf.py."
        )
        return False
    return True


def _clean_scratch() -> None:
    """Remove Nuitka intermediate directories from BUILD_DIR (in case --remove-output
    left anything behind), so they never end up in the release zip."""
    if not BUILD_DIR.exists():
        return
    for child in BUILD_DIR.iterdir():
        if child.is_dir() and (
            child.name in SCRATCH_NAMES or child.name.endswith(SCRATCH_SUFFIXES)
        ):
            shutil.rmtree(child, ignore_errors=True)


def build_exe() -> bool:
    print("=== Building beamtel.exe with Nuitka ===")
    if not check_build_inputs():
        return False

    nuitka_args = [
        "--nofollow-import-to=IPython",
        "--noinclude-unittest-mode=error",
        "--noinclude-pytest-mode=error",
        "--noinclude-setuptools-mode=error",
        "--output-dir=build",
        "--remove-output",
        "--lto=yes",
        "--include-data-file=hrtf_kemar_horizontal.npz=hrtf_kemar_horizontal.npz",
        "--include-package=mss",
        "--nofollow-import-to=h5py",
        "--nofollow-import-to=pygame",
        "--nofollow-import-to=scipy",
        "--nofollow-import-to=matplotlib",
        "--nofollow-import-to=tkinter",
        "--nofollow-import-to=PIL",
        "--nofollow-import-to=pytest",
        "--nofollow-import-to=setuptools",
        "--nofollow-import-to=pip",
        "--standalone",
        "--onefile",
        "--onefile-no-compression",
        "--onefile-cache-mode=cached",
        "--onefile-tempdir-spec={PROGRAM_DIR}/.appdata",
        "--assume-yes-for-downloads",
        f"--jobs={NUITKA_JOBS}",
        "--windows-console-mode=disable",
        "--windows-uac-admin",
    ]

    prism_args = prism_nuitka_args()
    if prism_args is None:
        return False
    nuitka_args.extend(prism_args)

    # Machine-specific: compiler backend. "msvc" uses Nuitka's Windows default (no flag).
    if COMPILER == "clang":
        nuitka_args.append("--clang")

    # Machine-specific: UPX compression. Skip (rather than fail) if the binary is missing.
    if USE_UPX:
        if Path(UPX_BINARY).exists():
            nuitka_args.append("--plugin-enable=upx")
            nuitka_args.append(f"--upx-binary={UPX_BINARY}")
        else:
            print(
                f"WARNING: USE_UPX is set but UPX binary not found at {UPX_BINARY};\n"
                "         building without UPX compression."
            )

    result = subprocess.run(
        ["uv", "run", "nuitka", *nuitka_args, "beamtel.py"],
        cwd=PROJECT_DIR,
    )
    if result.returncode != 0:
        print(f"\nERROR: Nuitka build failed (exit code {result.returncode})")
        return False

    exe = BUILD_DIR / "beamtel.exe"
    if not exe.exists():
        print(f"ERROR: Build succeeded but {exe} not found")
        return False

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    dest = OUTPUT_DIR / "beamtel.exe"
    # Nuitka already writes into BUILD_DIR, which is OUTPUT_DIR, so the copy is a
    # no-op there. Only copy when the two locations actually differ.
    if exe.resolve() != dest.resolve():
        shutil.copy2(exe, dest)
        print(f"Copied {exe.name} -> {dest}")
    else:
        print(f"beamtel.exe already in {OUTPUT_DIR}")

    readme = PROJECT_DIR / "README.md"
    if readme.exists():
        readme_dest = OUTPUT_DIR / "README.md"
        shutil.copy2(readme, readme_dest)
        print(f"Copied {readme.name} -> {readme_dest}")

    _clean_scratch()
    return True


def app_version() -> str:
    """The one hand-maintained version constant, read out of updater.py.

    By regex rather than by import: updater pulls in wx and the whole config
    stack, which a build script has no business loading. release.yml already
    reads it exactly this way and asserts it matches the pushed tag, so there is
    only ever one number to keep honest.
    """
    text = (PROJECT_DIR / "updater.py").read_text(encoding="utf-8")
    match = re.search(r'^APP_VERSION\s*=\s*"([^"]+)"', text, re.M)
    if not match:
        raise RuntimeError("APP_VERSION not found in updater.py")
    return match.group(1)


def package_mod() -> bool:
    print("=== Packaging mod ===")

    # Resolve the junction (or real folder) to the actual mod directory.
    mod_real = Path(os.path.realpath(MOD_JUNCTION))
    if not mod_real.exists():
        print(f"ERROR: Mod directory not found at {mod_real}")
        return False

    zip_path = OUTPUT_DIR / MOD_ZIP_NAME

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    version = app_version()
    stamp = json.dumps(
        {
            "version": version,
            "built_utc": datetime.datetime.now(datetime.timezone.utc)
            .replace(microsecond=0)
            .isoformat(),
        },
        indent=2,
    )

    file_count = 0
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for file in sorted(mod_real.rglob("*")):
            if file.is_file():
                arcname = file.relative_to(mod_real)
                if arcname.as_posix() == MOD_VERSION_MEMBER:
                    continue  # a stale stamp left in the junction by an old build
                zf.write(file, arcname)
                file_count += 1
                print(f"  + {arcname}")
        zf.writestr(MOD_VERSION_MEMBER, stamp)
        file_count += 1
        print(f"  + {MOD_VERSION_MEMBER} ({version})")

    print(f"\nPackaged {file_count} files -> {zip_path}")
    return True


def _is_scratch(rel: Path) -> bool:
    """True if a path under OUTPUT_DIR belongs to Nuitka scratch / runtime unpack."""
    for part in rel.parts:
        if part in SCRATCH_NAMES or part.endswith(SCRATCH_SUFFIXES):
            return True
    return False


def bundle_output() -> None:
    print("=== Bundling output directory ===")
    zip_path = OUTPUT_DIR / BUNDLE_NAME

    # Sweep any previous bundle -- including the dated ones older builds left
    # behind -- before the new zip is opened, so this can never delete the file
    # it is about to write.
    for existing in OUTPUT_DIR.glob("BeamNG_accessibility_mod*.zip"):
        existing.unlink()
        print(f"Removed existing {existing.name}")

    file_count = 0
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for file in sorted(OUTPUT_DIR.rglob("*")):
            if not file.is_file() or file == zip_path:
                continue
            arcname = file.relative_to(OUTPUT_DIR)
            if _is_scratch(arcname):
                continue
            zf.write(file, arcname)
            file_count += 1
            print(f"  + {arcname}")

    print(f"Bundled {file_count} files -> {zip_path}")


def main():
    parser = argparse.ArgumentParser(description="BEAM build script")
    parser.add_argument("--mod", action="store_true", help="Package mod only")
    parser.add_argument("--exe", action="store_true", help="Build exe only")
    args = parser.parse_args()

    do_exe = not args.mod
    do_mod = not args.exe

    # The mod junction is needed for packaging the mod; ensure it up front so the
    # build fails fast (and with a useful message) on a machine that lacks it.
    if do_mod:
        if not ensure_mod_junction():
            print("\nCannot proceed without the mod junction.")
            sys.exit(1)

    success = True

    if do_exe:
        if not build_exe():
            success = False
            if do_mod:
                print("Skipping mod packaging due to build failure.")
                sys.exit(1)

    if do_mod:
        if not package_mod():
            success = False

    if success:
        bundle_output()
        print("\nBuild complete.")
    else:
        print("\nBuild finished with errors.")
        sys.exit(1)


if __name__ == "__main__":
    main()
